name: plenum_app_support
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  google_fonts: ^4.0.1

dev_dependencies: 
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter
  
  

flutter_icons:
  android: true
  web:
    generate: true
    image_path: "assets/icon.png"

flutter: 
  uses-material-design: true
  assets:
    - assets/pl.png
    - assets/icon.png
